// phoneCountries.js
// Full country list for phone dropdown.

export const PC_PHONE_COUNTRIES = [
  { code: "ZZ", name: "International", dial: "" },
  { code: "AF", name: "Afghanistan", dial: "" },
  { code: "AX", name: "Åland Islands", dial: "" },
  { code: "AL", name: "Albania", dial: "" },
  { code: "DZ", name: "Algeria", dial: "" },
  { code: "AS", name: "American Samoa", dial: "" },
  { code: "AD", name: "Andorra", dial: "" },
  { code: "AO", name: "Angola", dial: "" },
  { code: "AI", name: "Anguilla", dial: "" },
  { code: "AG", name: "Antigua and Barbuda", dial: "" },
  { code: "AR", name: "Argentina", dial: "" },
  { code: "AM", name: "Armenia", dial: "" },
  { code: "AW", name: "Aruba", dial: "" },
  { code: "AC", name: "Ascension Island", dial: "" },
  { code: "AU", name: "Australia", dial: "" },
  { code: "AT", name: "Austria", dial: "" },
  { code: "AZ", name: "Azerbaijan", dial: "" },
  { code: "BS", name: "Bahamas", dial: "" },
  { code: "BH", name: "Bahrain", dial: "" },
  { code: "BD", name: "Bangladesh", dial: "" },
  { code: "BB", name: "Barbados", dial: "" },
  { code: "BY", name: "Belarus", dial: "" },
  { code: "BE", name: "Belgium", dial: "" },
  { code: "BZ", name: "Belize", dial: "" },
  { code: "BJ", name: "Benin", dial: "" },
  { code: "BM", name: "Bermuda", dial: "" },
  { code: "BT", name: "Bhutan", dial: "" },
  { code: "BO", name: "Bolivia", dial: "" },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba", dial: "" },
  { code: "BA", name: "Bosnia and Herzegovina", dial: "" },
  { code: "BW", name: "Botswana", dial: "" },
  { code: "BR", name: "Brazil", dial: "" },
  { code: "IO", name: "British Indian Ocean Territory", dial: "" },
  { code: "BN", name: "Brunei Darussalam", dial: "" },
  { code: "BG", name: "Bulgaria", dial: "" },
  { code: "BF", name: "Burkina Faso", dial: "" },
  { code: "BI", name: "Burundi", dial: "" },
  { code: "KH", name: "Cambodia", dial: "" },
  { code: "CM", name: "Cameroon", dial: "" },
  { code: "CA", name: "Canada", dial: "" },
  { code: "CV", name: "Cape Verde", dial: "" },
  { code: "KY", name: "Cayman Islands", dial: "" },
  { code: "CF", name: "Central African Republic", dial: "" },
  { code: "TD", name: "Chad", dial: "" },
  { code: "CL", name: "Chile", dial: "" },
  { code: "CN", name: "China", dial: "" },
  { code: "CX", name: "Christmas Island", dial: "" },
  { code: "CC", name: "Cocos (Keeling) Islands", dial: "" },
  { code: "CO", name: "Colombia", dial: "" },
  { code: "KM", name: "Comoros", dial: "" },
  { code: "CG", name: "Congo", dial: "" },
  {
    code: "CD",
    name: "Congo, Democratic Republic of the",
    dial: "",
  },
  { code: "CK", name: "Cook Islands", dial: "" },
  { code: "CR", name: "Costa Rica", dial: "" },
  { code: "CI", name: "Cote d'Ivoire", dial: "" },
  { code: "HR", name: "Croatia", dial: "" },
  { code: "CU", name: "Cuba", dial: "" },
  { code: "CW", name: "Curaçao", dial: "" },
  { code: "CY", name: "Cyprus", dial: "" },
  { code: "CZ", name: "Czech Republic", dial: "" },
  { code: "DK", name: "Denmark", dial: "" },
  { code: "DJ", name: "Djibouti", dial: "" },
  { code: "DM", name: "Dominica", dial: "" },
  { code: "DO", name: "Dominican Republic", dial: "" },
  { code: "EC", name: "Ecuador", dial: "" },
  { code: "EG", name: "Egypt", dial: "" },
  { code: "SV", name: "El Salvador", dial: "" },
  { code: "GQ", name: "Equatorial Guinea", dial: "" },
  { code: "ER", name: "Eritrea", dial: "" },
  { code: "EE", name: "Estonia", dial: "" },
  { code: "ET", name: "Ethiopia", dial: "" },
  { code: "FK", name: "Falkland Islands", dial: "" },
  { code: "FO", name: "Faroe Islands", dial: "" },
  { code: "FM", name: "Micronesia", dial: "" },
  { code: "FJ", name: "Fiji", dial: "" },
  { code: "FI", name: "Finland", dial: "" },
  { code: "FR", name: "France", dial: "" },
  { code: "GF", name: "French Guiana", dial: "" },
  { code: "PF", name: "French Polynesia", dial: "" },
  { code: "GA", name: "Gabon", dial: "" },
  { code: "GM", name: "Gambia", dial: "" },
  { code: "GE", name: "Georgia", dial: "" },
  { code: "DE", name: "Germany", dial: "" },
  { code: "GH", name: "Ghana", dial: "" },
  { code: "GI", name: "Gibraltar", dial: "" },
  { code: "GR", name: "Greece", dial: "" },
  { code: "GL", name: "Greenland", dial: "" },
  { code: "GD", name: "Grenada", dial: "" },
  { code: "GP", name: "Guadeloupe", dial: "" },
  { code: "GU", name: "Guam", dial: "" },
  { code: "GT", name: "Guatemala", dial: "" },
  { code: "GG", name: "Guernsey", dial: "" },
  { code: "GN", name: "Guinea", dial: "" },
  { code: "GW", name: "Guinea-Bissau", dial: "" },
  { code: "GY", name: "Guyana", dial: "" },
  { code: "HT", name: "Haiti", dial: "" },
  { code: "VA", name: "Vatican City", dial: "" },
  { code: "HN", name: "Honduras", dial: "" },
  { code: "HK", name: "Hong Kong", dial: "" },
  { code: "HU", name: "Hungary", dial: "" },
  { code: "IS", name: "Iceland", dial: "" },
  { code: "IN", name: "India", dial: "" },
  { code: "ID", name: "Indonesia", dial: "" },
  { code: "IR", name: "Iran", dial: "" },
  { code: "IQ", name: "Iraq", dial: "" },
  { code: "IE", name: "Ireland", dial: "" },
  { code: "IM", name: "Isle of Man", dial: "" },
  { code: "IL", name: "Israel", dial: "" },
  { code: "IT", name: "Italy", dial: "" },
  { code: "JM", name: "Jamaica", dial: "" },
  { code: "JP", name: "Japan", dial: "" },
  { code: "JE", name: "Jersey", dial: "" },
  { code: "JO", name: "Jordan", dial: "" },
  { code: "KZ", name: "Kazakhstan", dial: "" },
  { code: "KE", name: "Kenya", dial: "" },
  { code: "KI", name: "Kiribati", dial: "" },
  { code: "XK", name: "Kosovo", dial: "" },
  { code: "KW", name: "Kuwait", dial: "" },
  { code: "KG", name: "Kyrgyzstan", dial: "" },
  { code: "LA", name: "Laos", dial: "" },
  { code: "LV", name: "Latvia", dial: "" },
  { code: "LB", name: "Lebanon", dial: "" },
  { code: "LS", name: "Lesotho", dial: "" },
  { code: "LR", name: "Liberia", dial: "" },
  { code: "LY", name: "Libya", dial: "" },
  { code: "LI", name: "Liechtenstein", dial: "" },
  { code: "LT", name: "Lithuania", dial: "" },
  { code: "LU", name: "Luxembourg", dial: "" },
  { code: "MO", name: "Macao", dial: "" },
  { code: "MG", name: "Madagascar", dial: "" },
  { code: "MW", name: "Malawi", dial: "" },
  { code: "MY", name: "Malaysia", dial: "" },
  { code: "MV", name: "Maldives", dial: "" },
  { code: "ML", name: "Mali", dial: "" },
  { code: "MT", name: "Malta", dial: "" },
  { code: "MH", name: "Marshall Islands", dial: "" },
  { code: "MQ", name: "Martinique", dial: "" },
  { code: "MR", name: "Mauritania", dial: "" },
  { code: "MU", name: "Mauritius", dial: "" },
  { code: "YT", name: "Mayotte", dial: "" },
  { code: "MX", name: "Mexico", dial: "" },
  { code: "MD", name: "Moldova", dial: "" },
  { code: "MC", name: "Monaco", dial: "" },
  { code: "MN", name: "Mongolia", dial: "" },
  { code: "ME", name: "Montenegro", dial: "" },
  { code: "MS", name: "Montserrat", dial: "" },
  { code: "MA", name: "Morocco", dial: "" },
  { code: "MZ", name: "Mozambique", dial: "" },
  { code: "MM", name: "Myanmar", dial: "" },
  { code: "NA", name: "Namibia", dial: "" },
  { code: "NR", name: "Nauru", dial: "" },
  { code: "NP", name: "Nepal", dial: "" },
  { code: "NL", name: "Netherlands", dial: "" },
  { code: "NC", name: "New Caledonia", dial: "" },
  { code: "NZ", name: "New Zealand", dial: "" },
  { code: "NI", name: "Nicaragua", dial: "" },
  { code: "NE", name: "Niger", dial: "" },
  { code: "NG", name: "Nigeria", dial: "" },
  { code: "NU", name: "Niue", dial: "" },
  { code: "NF", name: "Norfolk Island", dial: "" },
  { code: "MK", name: "North Macedonia", dial: "" },
  { code: "MP", name: "Northern Mariana Islands", dial: "" },
  { code: "NO", name: "Norway", dial: "" },
  { code: "OM", name: "Oman", dial: "" },
  { code: "PK", name: "Pakistan", dial: "" },
  { code: "PW", name: "Palau", dial: "" },
  { code: "PS", name: "Palestine", dial: "" },
  { code: "PA", name: "Panama", dial: "" },
  { code: "PG", name: "Papua New Guinea", dial: "" },
  { code: "PY", name: "Paraguay", dial: "" },
  { code: "PE", name: "Peru", dial: "" },
  { code: "PH", name: "Philippines", dial: "" },
  { code: "PL", name: "Poland", dial: "" },
  { code: "PT", name: "Portugal", dial: "" },
  { code: "PR", name: "Puerto Rico", dial: "" },
  { code: "QA", name: "Qatar", dial: "" },
  { code: "RE", name: "Reunion", dial: "" },
  { code: "RO", name: "Romania", dial: "" },
  { code: "RU", name: "Russia", dial: "" },
  { code: "RW", name: "Rwanda", dial: "" },
  { code: "BL", name: "Saint Barthélemy", dial: "" },
  { code: "SH", name: "Saint Helena", dial: "" },
  { code: "KN", name: "Saint Kitts and Nevis", dial: "" },
  { code: "LC", name: "Saint Lucia", dial: "" },
  { code: "MF", name: "Saint Martin (French Part)", dial: "" },
  { code: "PM", name: "Saint Pierre and Miquelon", dial: "" },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    dial: "",
  },
  { code: "WS", name: "Samoa", dial: "" },
  { code: "SM", name: "San Marino", dial: "" },
  { code: "ST", name: "Sao Tome and Principe", dial: "" },
  { code: "SA", name: "Saudi Arabia", dial: "" },
  { code: "SN", name: "Senegal", dial: "" },
  { code: "RS", name: "Serbia", dial: "" },
  { code: "SC", name: "Seychelles", dial: "" },
  { code: "SL", name: "Sierra Leone", dial: "" },
  { code: "SG", name: "Singapore", dial: "" },
  { code: "SX", name: "Sint Maarten", dial: "" },
  { code: "SK", name: "Slovakia", dial: "" },
  { code: "SI", name: "Slovenia", dial: "" },
  { code: "SB", name: "Solomon Islands", dial: "" },
  { code: "SO", name: "Somalia", dial: "" },
  { code: "ZA", name: "South Africa", dial: "" },
  { code: "KR", name: "Korea", dial: "" },
  { code: "SS", name: "South Sudan", dial: "" },
  { code: "ES", name: "Spain", dial: "" },
  { code: "LK", name: "Sri Lanka", dial: "" },
  { code: "SD", name: "Sudan", dial: "" },
  { code: "SR", name: "Suriname", dial: "" },
  { code: "SJ", name: "Svalbard and Jan Mayen", dial: "" },
  { code: "SZ", name: "Swaziland", dial: "" },
  { code: "SE", name: "Sweden", dial: "" },
  { code: "CH", name: "Switzerland", dial: "" },
  { code: "SY", name: "Syria", dial: "" },
  { code: "TW", name: "Taiwan", dial: "" },
  { code: "TJ", name: "Tajikistan", dial: "" },
  { code: "TZ", name: "Tanzania", dial: "" },
  { code: "TH", name: "Thailand", dial: "" },
  { code: "TL", name: "Timor-Leste", dial: "" },
  { code: "TG", name: "Togo", dial: "" },
  { code: "TK", name: "Tokelau", dial: "" },
  { code: "TO", name: "Tonga", dial: "" },
  { code: "TT", name: "Trinidad and Tobago", dial: "" },
  { code: "TA", name: "Tristan da Cunha", dial: "" },
  { code: "TN", name: "Tunisia", dial: "" },
  { code: "TR", name: "Turkey", dial: "" },
  { code: "TM", name: "Turkmenistan", dial: "" },
  { code: "TC", name: "Turks and Caicos Islands", dial: "" },
  { code: "TV", name: "Tuvalu", dial: "" },
  { code: "UG", name: "Uganda", dial: "" },
  { code: "UA", name: "Ukraine", dial: "" },
  { code: "AE", name: "United Arab Emirates", dial: "" },
  { code: "GB", name: "United Kingdom", dial: "" },
  { code: "US", name: "United States", dial: "" },
  { code: "UY", name: "Uruguay", dial: "" },
  { code: "UZ", name: "Uzbekistan", dial: "" },
  { code: "VU", name: "Vanuatu", dial: "" },
  { code: "VE", name: "Venezuela", dial: "" },
  { code: "VN", name: "Vietnam", dial: "" },
  { code: "VG", name: "Virgin Islands, British", dial: "" },
  { code: "VI", name: "Virgin Islands, U.S.", dial: "" },
  { code: "WF", name: "Wallis and Futuna", dial: "" },
  { code: "EH", name: "Western Sahara", dial: "" },
  { code: "YE", name: "Yemen", dial: "" },
  { code: "ZM", name: "Zambia", dial: "" },
  { code: "ZW", name: "Zimbabwe", dial: "" },
];
